// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Dal;

namespace Project.Migrations
{
    [DbContext(typeof(MathDbContext))]
    partial class MathDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Models.LogMethod", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("InsertDate");

                    b.HasKey("Id");

                    b.ToTable("logMethods");
                });

            modelBuilder.Entity("Project.Models.LogReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate");

                    b.Property<int>("LogMethodId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LogMethodId");

                    b.ToTable("logReports");
                });

            modelBuilder.Entity("Project.Models.LogReport", b =>
                {
                    b.HasOne("Project.Models.LogMethod", "LogMethod")
                        .WithMany("LogReports")
                        .HasForeignKey("LogMethodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
